### ISSUE TITLE
Fix the missing changeset count issue for user reports endpoint

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/insights#23] opened 2022-05-18 13:54 UTC
Recently we modified the [user-reports endpoint](https://github.com/hotosm/galaxy-api/issues/210) so that the query runs faster. However with the new query update, @d-rita has noticed lesser count on buildings added and modified. Per chat, @omranlm and @itskshitiz321 identifies this is related to difference in timestamp consideration for changesets.

@omranlm is reviewing and will work on a fix/query if needed.

**Comment by omranlm** [comment] 2022-05-19 14:05
### Issue analysis 
The issue is happening as the code assumes that new changeset (bigger changeset #) are always appearing in sequence in osmChange replication files.

Since `changesetStats.py -U` command checks the max changeset Id in `all_changesets_stats` table, then calculating the stats for any changeset that appears in the `osm_element_history` table and > than max changeset id .. it turned on that some open changeset might still open and preserve its changeset id but being pushed into planet osm change files when the changeset is closed (which is with 24 hours as change setup can't be open for more than 24 hours)

This scenario leaks some changesets ID which presents in the  `osm_element_history`  table but their stats are not calculated in  `all_changesets_stats`  table (which runs on 1 hour frequency) 

### Missed changeset example
changeset id 120622710, have been missed during the calculation as it was open @ 10:01 and then closed @ 10:57 in the same day May 7th 2022.
![image.png](https://images.zenhubusercontent.com/620bb3575312f907812ad997/f842d81d-1bf4-41cb-af23-94ae21967fc9)
This pariculare changeset is exported by planet replication in [osm change file 005/046/559](https://planet.openstreetmap.org/replication/minute/005/046/559.osc.gz) although the close changeset IDs around 120622710 where exported in  [osm change file 005/046/506](https://planet.openstreetmap.org/replication/minute/005/046/506.osc.gz)

**Comment by omranlm** [comment] 2022-05-19 14:18
### Further insights for a solution
Since insights DB has a specific loading date and it is 5 Sept 2021, any changeset with date after might have a missed changeset in `all_changesets_stats` 

### How to find missing changesets
The following query would compare a certain range of changeset IDs between the `osm_element_history` table and `all_changesets_stats` table.
The example below focuses on changesets 114350000  and 114360000 and returned 1438 missed changeset
![image.png](https://images.zenhubusercontent.com/620bb3575312f907812ad997/1ddf50bf-d594-4389-a752-bc5fde463180)

> select t1.changeset
                            from (
                            select distinct osh.changeset
                                    from public.osm_element_history osh        
                                    where osh.changeset between 114350000  and 114360000
                                    and action != 'delete'
                                    ) t1
                            left outer join (
                                    select s.changeset
                                        from public.all_changesets_stats s                                      
                                        where s.changeset between 114350000  and 114360000
                                ) t2
                            on t1.changeset = t2.changeset
                            where t2.changeset is null 

>

**Comment by omranlm** [comment] 2022-05-24 14:47
### Solution

We have applied a solution to cover the missing changesets in 

1. the **on-going replication** and to cover missing changesets since project setup (5 Sept 2021 in HOTOSM setup for the OSM Galaxy project) and 
2. in the p**revious loaded OSM historical elements/changesets**

For 1: it is the same 1 hour frequency command ` changesetStats.py -U ` with a new feature to scan the recent 24 hours which would guarantee any open change should have been closed as [maximum open time for a change set in OSM is 24 hours ](https://wiki.openstreetmap.org/wiki/Changeset#:~:text=Changesets%20have%20a%20maximum%20capacity,timeout%20(currently%201%20hour).)
Example of how the changesetStats.log would look like:
![image](https://user-images.githubusercontent.com/39491329/170063319-df9524a1-9524-4b53-9ba2-1e2c729a841d.png)


For 2: it is a 1 time command `changesetStats.py -U -F -s CHANGESET_ID` which will update `all_changesets_stats` table fixing (calculating and inserting missing changesets) and starts from -s changeset specific id backwards till changeset 0 -- (we are scanning every 5000 changeset in waves for logging and lighter query load)
Furthermore, this command  `changesetStats.py -U -F -s CHANGESET_ID` can be used to calculate changeset stats for newly loaded country when a new country is loaded.
The command logs would look like the following, scanning 5000 changesets takes~ 30 seconds 
![image](https://user-images.githubusercontent.com/39491329/170064375-d820cfaf-956b-4e30-8e67-93e0bc8f5ce5.png)


The final output from  `changesetStats.py -U -F -s CHANGESET_ID` , and it took ~11 hours to scan 
![image](https://user-images.githubusercontent.com/39491329/170212571-1a8a7dd5-e9e7-4e8b-b9b4-cb14423e0dd7.png)


The solution commits for reference:
https://github.com/hotosm/insights/commit/1a8b2a92d2de56e60b99ce45f074fee3f8e7f03a
https://github.com/hotosm/insights/commit/59e3f75e5ccaf6f46bc78e1e5a53cde18feb0320

**Closed as completed** 2022-05-25 08:05 UTC
